from pygame.constants import*

#CONSTANTES TOUCHES
TIR=K_SPACE
HAUT=K_UP
DROITE=K_RIGHT
GAUCHE=K_LEFT
BAS=K_DOWN
PAUSE=K_p

#CONSTANTES SCORE
SCORE_BASE=80
SCORE_ENNEMI_2=10
ENNEMI_1_ZIGZAG=20
SCORE_MINIBOSS=80

#VITESSE DEPLACEMENT
VITESSE_PERSO=5
VITESSE_ENNEMI_1=2.5
VITESSE_ENNEMI_2_Y=2.5
VITESSE_ENNEMI_2_X=1.5
VITESSE_FOND=1
